import os
import sqlite3
from tracker.productivity_engine import get_productivity_report
from tracker.anomaly_engine import get_anomaly_message

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, '..', 'tracker', 'aura_memory.db')

# This will collect current system snapshots from database
def get_system_context():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    fields = ['battery', 'cpu_usage', 'ram_usage', 'wifi_signal', 'active_apps', 'time_stamp']

    data = {
        col : cursor.execute(f"SELECT {col} FROM snapshots").fetchall()
        for col in fields
    }

    conn.close()

    return f'''battery levels : {data['battery']},
    cpu_usage track : {data['cpu_usage']},
    ram_usage track : {data['ram_usage']},
    wifi_signal track : {data['wifi_signal']},
    active_apps history : {data['active_apps']},
    time_stamps {data['time_stamp']}'''

# This will collect user patterns 
def get_user_context():
    report = get_productivity_report()

    return f'''total user sessions : {report['total_session']},
    most productive day : {report['most_productive_day']},
    peak hours : {report['peak_hours']},
    average session duration : {report['avg_duration']}'''

# This will give the check of current login
def get_anomaly_context():
    login = get_anomaly_message()

    return login

# master function
def build_full_context():
    system = get_system_context()
    user = get_user_context()
    anomaly = get_anomaly_context()

    return f'''Hey this is the everything needed as to know user:
    This is all the system snapshots from database taken after every 5 minutes : {system},
    This is the productivity report of user : {user},
    This is the anomaly message about login generated by anomaly engine : {anomaly} take the useful information from this.'''